apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "autoannotation.fullname" . }}-ca-issuer
spec:
  ca:
    secretName: {{ include "autoannotation.fullname" . }}-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "autoannotation.fullname" . }}-cert
  labels:
    {{- include "autoannotation.labels" . | nindent 4 }}
spec:
  secretName: {{ include "autoannotation.fullname" . }}
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - {{ .Values.organization }}
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS1
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  issuerRef:
    name: {{ include "autoannotation.fullname" . }}-ca-issuer
    kind: ClusterIssuer
  commonName: {{ include "autoannotation.fullname" . }}
  dnsNames:
    - {{ include "autoannotation.fullname" . }}
    - {{ include "autoannotation.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "autoannotation.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
