name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tag name
        id: get_tag
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Metadata for Docker image
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/parraletz/webhookmuttating-example
          tags: |
            ghcr.io/parraletz/webhookmuttating-example:${{ github.sha }}
            ghcr.io/parraletz/webhookmuttating-example:latest
            ghcr.io/parraletz/webhookmuttating-example:${{ steps.get_tag.outputs.tag_name }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
