name: Semantic Release

on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install UV
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302

      - name: Install dependencies
        run: uv sync

      - name: Run uv sync
        run: uv sync --extra build

      - name: semantic-release
        id: version
        env:
          GH_TOKEN: "none"
        run: uv run semantic-release -v version --no-changelog --no-commit --no-tag

    outputs:
      new-release-detected: ${{ steps.version.outputs.released }}
      new-release-version: ${{ steps.version.outputs.version }}
      new-release-tag: ${{ steps.version.outputs.tag }}
      new-release-is-prerelease: ${{ steps.version.outputs.is_prerelease }}
