name: Build
on: [push, pull_request]

env:
  PYTHONPATH: .

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Install dependencies
        run: |
          uv sync
      - name: Run tests
        run: |
          uv run pytest -v
      - name: Run tests with coverage
        run: |
          export PYTHONPATH=.
          uv run pytest --cov=app --cov-report=xml --cov-fail-under=90
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     files: ./coverage.xml
      #     verbose: true
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}
