name: Build
on: [push, pull_request]

env:
  PYTHONPATH: .

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Install dependencies
        run: |
          uv sync
      - name: Run tests
        run: |
          uv run pytest -v
      - name: Create a tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}
        if: github.ref_name != 'main'
